# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ragflow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ragflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rragflow.proto\x12\x07ragflow\"M\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\x04\x64\x61ta\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_data\"T\n\x1a\x43reateKnowledgeBaseRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_description\"\\\n\x1b\x43reateKnowledgeBaseResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\x05kb_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_kb_id\"K\n\x15UploadDocumentRequest\x12\r\n\x05kb_id\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\".\n\x0b\x43hatRequest\x12\r\n\x05kb_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\"O\n\x0c\x43hatResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x06\x61nswer\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_answer2\xef\x01\n\x0bRagServices\x12`\n\x13\x43reateKnowledgeBase\x12#.ragflow.CreateKnowledgeBaseRequest\x1a$.ragflow.CreateKnowledgeBaseResponse\x12I\n\x0eUploadDocument\x12\x1e.ragflow.UploadDocumentRequest\x1a\x17.ragflow.StatusResponse\x12\x33\n\x04\x43hat\x12\x14.ragflow.ChatRequest\x1a\x15.ragflow.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ragflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSRESPONSE']._serialized_start=26
  _globals['_STATUSRESPONSE']._serialized_end=103
  _globals['_CREATEKNOWLEDGEBASEREQUEST']._serialized_start=105
  _globals['_CREATEKNOWLEDGEBASEREQUEST']._serialized_end=189
  _globals['_CREATEKNOWLEDGEBASERESPONSE']._serialized_start=191
  _globals['_CREATEKNOWLEDGEBASERESPONSE']._serialized_end=283
  _globals['_UPLOADDOCUMENTREQUEST']._serialized_start=285
  _globals['_UPLOADDOCUMENTREQUEST']._serialized_end=360
  _globals['_CHATREQUEST']._serialized_start=362
  _globals['_CHATREQUEST']._serialized_end=408
  _globals['_CHATRESPONSE']._serialized_start=410
  _globals['_CHATRESPONSE']._serialized_end=489
  _globals['_RAGSERVICES']._serialized_start=492
  _globals['_RAGSERVICES']._serialized_end=731
# @@protoc_insertion_point(module_scope)
